### ISSUE TITLE
[test_runner]: support MsTest

### ISSUE THREAD

**Issue by stemann** [Albacore/albacore#125] opened 2014-09-10 13:59 UTC
The following fails in test_runner.rb:137:
``` ruby
test_runner :tests do |tests|
  tests.files = FileList['**/*.Tests/bin/Release/*.Tests.dll']
  tests.exe = 'C:/Program Files (x86)/Microsoft Visual Studio 10.0/Common7/IDE/mstest.exe'
  tests.native_exe
end
```

test_runner.rb:137
``` ruby
          exe_rel = exe.relative_path_from dir
```

**Comment by joelwilson** [comment] 2015-01-08 18:45
Seems like the problem is that mstest.exe doesn't take a file argument, but Albacore assumes that the test runner does. mstest expects the test file to be passed in the `/testcontainer:` option:

    mstest /testcontainer:mytestproject.dll

Output from `mstest /help`:

	Microsoft (R) Test Execution Command Line Tool Version 12.0.21005.1
	Copyright (c) Microsoft Corporation. All rights reserved.

	Usage:                      MSTest.exe [options].

	Description:                        Run tests in test files.

	Options:

	  <blahblahblah>

	  /testcontainer:[file name]        Load a file that contains tests. You can
										Specify this option more than once to
										load multiple test files.
										Examples:
										  /testcontainer:mytestproject.dll
										  /testcontainer:loadtest1.loadtest

Error on run:

	rake aborted!
	Albacore::CommandFailedError: Command failed with status (1):
	  ..\..\..\..\..\..\..\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe myprojecttests.dll
	Microsoft (R) Test Execution Command Line Tool Version 12.0.21005.1
	Copyright (c) Microsoft Corporation. All rights reserved.

	Invalid switch "myprojecttests.dll".
	For switch syntax, type "MSTest /help"

Ommitting `test.files` and giving the task the `/testcontainer` parameter with the dll causes it to not run at all:

	namespace :tests do
	  desc 'Run the unit tests'
	  test_runner :unit => :buildtests do |tests|
		tests.exe = 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe'
		tests.add_parameter '/testcontainer:MyProjectTests.dll'
	  end
 
    task :tests => :'tests:unit'

Run:

        > rake tests

	C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe /verbosity:minimal mytestproject.csproj /target:Build /property:Configuration=Release;
	Microsoft (R) Build Engine version 4.0.30319.36242
	[Microsoft .NET Framework, version 4.0.30319.0]
	Copyright (C) Microsoft Corporation. All rights reserved.

		</build output messages>

	** Execute tests:unit
	** Execute tests

At this point, I'm thinking of just converting to nunit or xunit, but it would be nice if albacore supported mstest. There are a lot of people out there using mstest, and requiring people who want to use albacore to adopt a different test framework isn't good imo.

**Comment by haf** [comment] 2015-01-08 20:04
I'm not using mstest, but I'm very willing to even take a large refactoring of the test_runner. Since I nowadays only code in F#, I tend to use Fuchu.

**Comment by haf** [comment] 2015-06-18 10:09
I'm closing this due to lack of community interest/interaction. If you'd like this to be resolved, please send a PR; I'm more than happy to merge such PRs.

**Closed by haf** 2015-06-18 10:09 UTC
Labels: minor_bug
